### ISSUE TITLE
debian 10 tornado4 rename patch breaks upstream

### ISSUE THREAD

**Issue by cyril-s** [saltstack/salt-pack-py3#188]
# Description
Salt minion installed from [saltstack python3 debian repo](https://repo.saltstack.com/#debian)  and configured with http proxy throws `NameError` when invoking `pkg.mod_repo`.
```sh
$ salt \* pkg.mod_repo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main" key_url="https:/
/www.postgresql.org/media/keys/ACCC4CF8.asc"
test-minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1672, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/aptpkg.py", line 2253, in mod_repo
        fn_ = __salt__['cp.cache_file'](key_url, saltenv)
      File "/usr/lib/python3/dist-packages/salt/modules/cp.py", line 515, in cache_file
        result = _client().cache_file(path, saltenv, source_hash=source_hash)
      File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 196, in cache_file
        path, '', True, saltenv, cachedir=cachedir, source_hash=source_hash)
      File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 697, in get_url
        **get_kwargs
      File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 537, in query
        AsyncHTTPClient.configure('CurlAsyncHTTPClient')
    NameError: name 'AsyncHTTPClient' is not defined
```
But salt minion [set up directly from upstream](https://docs.saltstack.com/en/latest/topics/development/hacking.html) -- doesn't.

# Cause

It seems that debian 10 python3 tornado4 patch `salt-renamed-python3-tornado4.patch` causing this problem.
It is present in `2019_2`, `2019_2_1`, `2019_2_2`:

```sh
$ tar -tf file_roots/pkg/salt/2019_2/debian10/spec/salt_debian.tar.xz  | grep patch
debian/patches/
debian/patches/salt-renamed-python3-tornado4.patch
debian/patches/series
$ tar -tf file_roots/pkg/salt/2019_2_1/debian10/spec/salt_debian.tar.xz  | grep patch
debian/patches/
debian/patches/salt-renamed-python3-tornado4.patch
debian/patches/series
$ tar -tf file_roots/pkg/salt/2019_2_2/debian10/spec/salt_debian.tar.xz  | grep patch
debian/patches/
debian/patches/salt-renamed-python3-tornado4.patch
debian/patches/series
```

For `2019_2_3` it some empty file instead

```sh
$ tar -tvf file_roots/pkg/salt/2019_2_3/debian10/spec/salt_debian.tar.xz  | grep patch
drwxr-xr-x david/david       0 2020-01-22 22:15 debian/patches/
-rw-r--r-- david/david      29 2020-01-22 22:14 debian/patches/series
-rw-r--r-- david/david       0 2020-01-22 22:15 debian/patches/salt-neon-rc2-tornado4.patch
```

but it is present in [repo](https://repo.saltstack.com/py3/debian/10/amd64/2019.2/pool/main/s/salt/) (`salt_2019.2.3+ds-1.debian.tar.xz`)
and is definitely applied on the latest `2019_2_3` release for debian 10.

```sh
$ tar -tvf salt_2019.2.3+ds-1.debian.tar.xz | grep patch
drwxr-xr-x 0/0               0 2019-10-16 22:50 debian/patches/
-rw-r--r-- 0/0          121282 2019-10-16 22:50 debian/patches/salt-renamed-python3-tornado4.patch
-rw-r--r-- 0/0              36 2019-10-16 22:50 debian/patches/series
```

Regarding problem described in this issue, patch strips full module path in this chunk incorrectly
because `AsyncHTTPClient` wasn't impoerted directly.

```diff
-            tornado.httpclient.AsyncHTTPClient.configure('tornado.curl_httpclient.CurlAsyncHTTPClient')
+            AsyncHTTPClient.configure('CurlAsyncHTTPClient')
```

<details><summary>Patch contents for salt/utils/http.py</summary>
<p>

```diff
--- a/salt/utils/http.py
+++ b/salt/utils/http.py
@@ -66,15 +66,24 @@
 # pylint: enable=import-error,no-name-in-module

 # Don't need a try/except block, since Salt depends on tornado
-import tornado.httputil
-import tornado.simple_httpclient
-from tornado.httpclient import HTTPClient
-
 try:
-    import tornado.curl_httpclient
-    HAS_CURL_HTTPCLIENT = True
+    from tornado4.httputil import url_concat
+    from tornado4.simple_httpclient import SimpleAsyncHTTPClient
+    from tornado4.httpclient import HTTPClient, HTTPError
+    try:
+        from tornado4.curl_httpclient import CurlAsyncHTTPClient
+        HAS_CURL_HTTPCLIENT = True
+    except ImportError:
+        HAS_CURL_HTTPCLIENT = False
 except ImportError:
-    HAS_CURL_HTTPCLIENT = False
+    from tornado.httputil import url_concat
+    from tornado.simple_httpclient import SimpleAsyncHTTPClient
+    from tornado.httpclient import HTTPClient, HTTPError
+    try:
+        from tornado.curl_httpclient import CurlAsyncHTTPClient
+        HAS_CURL_HTTPCLIENT = True
+    except ImportError:
+        HAS_CURL_HTTPCLIENT = False
 
 try:
     import requests
@@ -212,7 +221,7 @@
 
     # Some libraries don't support separation of url and GET parameters
     # Don't need a try/except block, since Salt depends on tornado
-    url_full = tornado.httputil.url_concat(url, params) if params else url
+    url_full = url_concat(url, params) if params else url
 
     if ca_bundle is None:
         ca_bundle = get_ca_bundle(opts)
@@ -525,12 +534,12 @@
                 log.error(ret['error'])
                 return ret
 
-            tornado.httpclient.AsyncHTTPClient.configure('tornado.curl_httpclient.CurlAsyncHTTPClient')
+            AsyncHTTPClient.configure('CurlAsyncHTTPClient')
             client_argspec = salt.utils.args.get_function_argspec(
-                    tornado.curl_httpclient.CurlAsyncHTTPClient.initialize)
+                    CurlAsyncHTTPClient.initialize)
         else:
             client_argspec = salt.utils.args.get_function_argspec(
-                    tornado.simple_httpclient.SimpleAsyncHTTPClient.initialize)
+                    SimpleAsyncHTTPClient.initialize)
 
         supports_max_body_size = 'max_body_size' in client_argspec.args
 
@@ -564,7 +573,7 @@
                 if supports_max_body_size \
                 else HTTPClient()
             result = download_client.fetch(url_full, **req_kwargs)
-        except tornado.httpclient.HTTPError as exc:
+        except HTTPError as exc:
             ret['status'] = exc.code
             ret['error'] = six.text_type(exc)
             return ret
```

</p>
</details>

# System info

<details><summary>Minion config</summary>
<p>

```yaml
master: 192.168.122.1
master_tries: -1
auth_tries: -1
autosign_grains:
- salt_autoaccept_pwd
grains:
  salt_autoaccept_pwd: "bla"
proxy_host: service-proxy.example.com
proxy_port: 3128
no_proxy: ['localhost','127.0.0.1','.example.com']
```

</p>
</details>

<details><summary>Minion version</summary>
<p>

```
Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10.1
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.1
```

</p>
</details>

---
Update for Feb 11 2020: this issue does not apply for salt v3000 since it has vendored tornado

**Comment by bryceml** [comment]
Is this still an issue on newer versions? 2019.2 is no longer supported.
